### ISSUE TITLE
the code of content_planner not provided

### ISSUE THREAD

**Issue by jiangliqin** [yxuansu/PlanGen#1]
Hi,I'm greatly interested in your "Plan-then-Generate" work,but the content planner mentioned in your paper is not provided code,i doubt how to joint the  Bert model and CRF to generate the conent planner.I'm looking forward to reading  your code in this part.Could you please provide the complete code as soon as possible?Thanks~

**Comment by yxuansu** [comment]
> Hi,I'm greatly interested in your "Plan-then-Generate" work,but the content planner mentioned in your paper is not provided code,i doubt how to joint the Bert model and CRF to generate the conent planner.I'm looking forward to reading your code in this part.Could you please provide the complete code as soon as possible?Thanks~

Hello, thank you very much for your interest! Due to several intensive deadlines, I might not have time to update the code in a month or so. However, if you are interested in jointly applying CRF and BERT. You can check out my other repo here (https://github.com/yxuansu/NAG-BERT) which shows how to use BERT+CRF to address text generation tasks. 

Hope my response could help you. I will try my best to update the planner code as soon as possible! Feel free to ask me if you have further questions. :)

**Comment by jiangliqin** [comment]
ok,thanks a lot!I will read your NAG-BERT repo as soon as possible

**Comment by yxuansu** [comment]
> ok,thanks a lot!I will read your NAG-BERT repo as soon as possible

Cool! Feel free to ask me if you have more questions. :)

**Comment by llllearner** [comment]
> 

hi, have you figure out the content planner code?

**Comment by yxuansu** [comment]
Hi @jiangliqin and @YHL-Lab,

Sorry for my very late update!

I have updated the part of the content planner. Please let me know if you have further questions!

Best,

Yixuan
